### ISSUE TITLE
First Session

### ISSUE THREAD

**Issue by gurneetbhatia** [DSC-UOM/Personal-site-series#1]
- [x] Intro to Angular CLI (generate an app from CLI)
- [x] Use npm to install the mdbootstrap library and configure it (https://material.angular.io/)
- Go over the basic structure of an Angular app (modules, components, packages, etc.)
- [x] Generate Home component from CLI
  - [x] Design a basic home page
- Intro to Angular routing module
  - [x] Connect the home component to the app
- [x] Generate a navbar from CLI
  - [x] Design the navbar

The branch associated with this issue is `sessions/one`

**Comment by HudsonFinn** [comment]
Looks good to me!

**Comment by gurneetbhatia** [comment]
I've completed all the specifications for this issue, and it looks like this at the end of it:
![Screenshot_62](https://user-images.githubusercontent.com/36604284/94371741-b09a8600-00f0-11eb-9422-8ed7a4d37a5b.png)
